name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Dọn Docker và cache trước build
      - name: Clean Docker
        run: |
          docker system prune -af
          docker volume prune -f
          docker image prune -f
          docker container prune -f

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 Build Docker image không cache và push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: phong163/gs25_all:latest
          build-args: |
            PIP_NO_CACHE_DIR=1
          no-cache: true
