name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # hoặc tên branch chính của bạn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prune Docker system
        run: |
          docker system prune -af
          docker volume prune -f
      - name: Remove dangling images
        run: docker image prune -f
      
      - name: Remove stopped containers
        run: docker container prune -f

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # platforms: linux/arm64  # Chỉ định build cho linux/arm64
          push: true
          tags: phong163/gs25_all:latest
